version: "3"
services:
  node-app: 
    container_name: smart-pharmacy-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  mysql-data: